all_models_variables = ['cost', 
                                    'points_per_game',
                                    'form', 
                                    'selected_by_percent', 
                                    'team_strength', 
                                    #'last_season_points_per_minute', 
                                    #'two_seasons_ago_points_per_minute', 
                                    'fixture_difficulty', 
                                    'is_home',
                                    'is_slightly_injured',
                                    'previous_fixtures_total_points_2',
                                    'previous_fixtures_total_points_average',
                                    'previous_fixtures_transfers_balance_2',
                                    'previous_fixtures_transfers_balance_average',
                                    'previous_fixtures_minutes_2',
                                    'previous_fixtures_minutes_average',
                                    'previous_fixtures_bonus_2',
                                    'previous_fixtures_bonus_average',
                                    'previous_fixtures_influence_2',
                                    'previous_fixtures_influence_average',
                                    'previous_fixtures_creativity_2',
                                    'previous_fixtures_creativity_average',
                                    'previous_fixtures_threat_2',
                                    'previous_fixtures_threat_average',
                                    'previous_fixtures_ict_index_2',
                                    'previous_fixtures_ict_index_average']
                                    #,
                                    #'previous_fixtures_open_play_crosses_2',
                                    #'previous_fixtures_open_play_crosses_average']
                 
goalkeeper_specific_variables = ['previous_fixtures_clean_sheets_2',
                                    'previous_fixtures_clean_sheets_average',
                                    'previous_fixtures_goals_conceded_2',
                                    'previous_fixtures_goals_conceded_average',
                                    'previous_fixtures_penalties_saved_2',
                                    'previous_fixtures_penalties_saved_average',
                                    'previous_fixtures_saves_2',
                                    'previous_fixtures_saves_average']
                                    
defender_specific_variables = ['previous_fixtures_goals_scored_2',
                                    'previous_fixtures_goals_scored_average',
                                    'previous_fixtures_assists_2',
                                    'previous_fixtures_assists_average',
                                    'previous_fixtures_clean_sheets_2',
                                    'previous_fixtures_clean_sheets_average',
                                    'previous_fixtures_goals_conceded_2',
                                    'previous_fixtures_goals_conceded_average',
                                    'previous_fixtures_big_chances_created_2',
                                    'previous_fixtures_big_chances_created_average',
                                    'previous_fixtures_clearances_blocks_interceptions_2',
                                    'previous_fixtures_clearances_blocks_interceptions_average',
                                    'previous_fixtures_recoveries_2',
                                    'previous_fixtures_recoveries_average',
                                    'previous_fixtures_key_passes_2',
                                    'previous_fixtures_key_passes_average',
                                    'previous_fixtures_tackles_2',
                                    'previous_fixtures_tackles_average',
                                     'previous_fixtures_winning_goals_2',
                                    'previous_fixtures_winning_goals_average',
                                    'previous_fixtures_errors_leading_to_goal_2',
                                    'previous_fixtures_errors_leading_to_goal_average',
                                    'previous_fixtures_errors_leading_to_goal_attempt_2',
                                    'previous_fixtures_errors_leading_to_goal_attempt_average',
                                    'previous_fixtures_tackled_2',
                                    'previous_fixtures_tackled_average',
                                     'previous_fixtures_fouls_2',
                                    'previous_fixtures_fouls_average',
                                    'previous_fixtures_dribbles_2',
                                    'previous_fixtures_dribbles_average']

midfielder_specific_variables = ['previous_fixtures_goals_scored_2',
                                    'previous_fixtures_goals_scored_average',
                                    'previous_fixtures_assists_2',
                                    'previous_fixtures_assists_average',
                                    'previous_fixtures_clean_sheets_2',
                                    'previous_fixtures_clean_sheets_average',
                                    'previous_fixtures_goals_conceded_2',
                                    'previous_fixtures_goals_conceded_average',
                                    'previous_fixtures_big_chances_created_2',
                                    'previous_fixtures_big_chances_created_average',
                                    'previous_fixtures_clearances_blocks_interceptions_2',
                                    'previous_fixtures_clearances_blocks_interceptions_average',
                                    'previous_fixtures_recoveries_2',
                                    'previous_fixtures_recoveries_average',
                                    'previous_fixtures_key_passes_2',
                                    'previous_fixtures_key_passes_average',
                                    'previous_fixtures_tackles_2',
                                    'previous_fixtures_tackles_average',
                                     'previous_fixtures_winning_goals_2',
                                    'previous_fixtures_winning_goals_average',
                                    'previous_fixtures_big_chances_missed_2',
                                    'previous_fixtures_big_chances_missed_average',
                                    'previous_fixtures_errors_leading_to_goal_2',
                                    'previous_fixtures_errors_leading_to_goal_average',
                                    'previous_fixtures_errors_leading_to_goal_attempt_2',
                                    'previous_fixtures_errors_leading_to_goal_attempt_average',
                                    'previous_fixtures_tackled_2',
                                    'previous_fixtures_tackled_average',
                                     'previous_fixtures_fouls_2',
                                    'previous_fixtures_fouls_average',
                                    'previous_fixtures_dribbles_2',
                                    'previous_fixtures_dribbles_average']

forward_specific_variables = ['previous_fixtures_goals_scored_2',
                                    'previous_fixtures_goals_scored_average',
                                    'previous_fixtures_assists_2',
                                    'previous_fixtures_assists_average',
                                    'previous_fixtures_big_chances_created_2',
                                    'previous_fixtures_big_chances_created_average',
                                    'previous_fixtures_key_passes_2',
                                    'previous_fixtures_key_passes_average',
                                    'previous_fixtures_winning_goals_2',
                                    'previous_fixtures_winning_goals_average',
                                    'previous_fixtures_big_chances_missed_2',
                                    'previous_fixtures_big_chances_missed_average',
                                    'previous_fixtures_tackled_2',
                                    'previous_fixtures_tackled_average',
                                    'previous_fixtures_fouls_2',
                                    'previous_fixtures_fouls_average',
                                    'previous_fixtures_dribbles_2',
                                    'previous_fixtures_dribbles_average']


# =============================================================================
# collections_undependent_variables = {'goalkeeper-samples': ['cost', 
#                                                             'points_per_game',
#                                                             'form', 
#                                                             'selected_by_percent', 
#                                                             'team_strength', 
#                                                             'last_season_points_per_minute', 
#                                                             'two_seasons_ago_points_per_minute', 
#                                                             'fixture_difficulty', 
#                                                             'is_home',
#                                                             'is_slightly_injured'],
#                                      'defender-samples': [],
#                                      'midfielder-samples': [],
#                                      'forward-samples': []}
# =============================================================================